#!/bin/bash

input=$1
output=/tmp/yali.pl

echo "consult(yali)." > $output

cat $input | \
sed 's/ \+/,/g' | \
sed 's/(/\[/g'  | \
sed 's/)/\]/g'  | \
sed 's/^\(.*\);.*$/\1/' | \
sed '/^$/d' | \
sed 's/\(.*\)/Execute = eval(\[\],\[\],\1,Eval,Funs), Execute.\n/' >> $output

cat $output | swipl 

