#!/bin/bash

input=$1
output=/tmp/yali.pl

echo -e "consult(yali).\nnb_setval(fo,[])." > $output

cat $input | sed 's/;.*$//' | \
awk 'BEGIN{FS=""}{
    for(i=1;i<=NF;i++) {
        if($(i) == "(") {
            ++b
        } 
        printf "%s",$(i)
	if($(i) == ")") {
            --b
            if(b == 0)        
                printf "\n" 
	}
    }
    if(b == 0)        
        printf "\n" 
    else
        printf " "
}' | \
sed 's/^ *//' | \
sed 's/ *$//' | \
sed 's/ \+/,/g' | \
sed 's/(/\[/g'  | \
sed 's/)/\]/g'  | \
sed '/^$/d' | \
sed 's/\(.*\)/Execute = eval(\1,Eval,\[\],Fin,Funs), b_getval(fo, Fin), Execute, nb_setval(fo, Funs).\n/' >> $output

cat $output | swipl 

